# yaml-language-server: $schema=../../../schemas/k8s/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  selector: {}
  template:
    spec:
      containers:
      - env:
        - name: TZ
          value: America/New_York
        image: eclipse-mosquitto:2.0.11
        name: mqtt
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/config
          name: mqtt
          subPath: config
        - mountPath: /mosquitto/data
          name: mqtt
          subPath: data
        - mountPath: /mosquitto/logs
          name: logs
      volumes:
      - name: mqtt
        hostPath:
          path: /mnt/k8s/mqtt
          type: Directory
      - emptyDir: {}
        name: logs
