# yaml-language-server: $schema=../../../schemas/k8s/ingress-networking-v1.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-red
  namespace: default
spec:
  rules:
  - host: node-red.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-red
            port:
              name: node-red-http
  - host: node-red.home.ericcodes.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-red
            port:
              name: node-red-http
