# yaml-language-server: $schema=../../../schemas/k8s/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: portal
  name: portal
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/k8s/portal2
    server: 192.168.1.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
