output:
  - platform: ledc
    pin:
      number: GPIO8
      inverted: true
      mode: output
    id: blueLED


light:
  - id: blue_light
    platform: monochromatic
    name: "Blue Light"
    output: blueLED

    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
