# yaml-language-server: $schema=../../../schemas/k8s/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/k8s/mqtt
    server: 192.168.1.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
