# yaml-language-server: $schema=../../../schemas/k8s/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  ports:
  - name: mqtt-mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  type: LoadBalancer
