# yaml-language-server: $schema=../../../schemas/k8s-v1.19.12/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  selector:
    matchLabels:
      name: mqtt
  storageClassName: nas
